unix {
  nodaemon
  log /var/log/vpp/vpp.log
  full-coredump
  cli-listen /run/vpp/cli.sock
  gid vpp
}

# Use DPDK with kernel-bound devices (uio_pci_generic instead of vfio-pci)
dpdk {
  uio-driver uio_pci_generic
  dev 0000:15:00.0 {
    name upf-n3
    num-rx-queues 16
    num-tx-queues 8 
  }
  #dev 0000:13:00.0 {
  #  name upf-n6
  #  num-rx-queues 16
  #  num-tx-queues 8
  #}
}

# Enable UPF plugin
upf {
  # UPF specific configuration
}